name: Build executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'

      - name: Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libx11-dev libxtst-dev libpng++-dev

      - name: Node dependencies
        run: npm install

      - name: Install pkg
        run: npm install -g pkg

      - name: Build
        run: npm run build

      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

      - name: Determine version
        id: determine_version
        run: echo "::set-output name=GIT_VERSION::$(git describe --tags --always)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.determine_version.outputs.GIT_VERSION }}
          release_name: Release ${{ steps.determine_version.outputs.GIT_VERSION }}
          body: |
            Release ${{ steps.determine_version.outputs.GIT_VERSION }}.
          draft: false
          prerelease: false

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/twitch_key_control-linux
          asset_name: twitch_key_control-linux
          asset_content_type: application/octet-stream

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/twitch_key_control-macos
          asset_name: twitch_key_control-macos
          asset_content_type: application/octet-stream

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/twitch_key_control-win.exe
          asset_name: twitch_key_control-win.exe
          asset_content_type: application/octet-stream
